#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e

#DO NOT GO OVER 4
MAX_CONCURRENT_BUILDS=1

# Check if 'builds' folder exists, create it if not
if [ ! -d "./builds" ]; then
    echo "'builds' folder not found. Creating it..."
    mkdir -p ./builds
else
    echo "'builds' folder already exists removing it."
    rm -rf ./builds
    mkdir -p ./builds
fi

cd ./builds
ROOT_DIR="GKI-AIO-$(date +'%Y-%m-%d-%I-%M-%p')-release"
echo "Creating root folder: $ROOT_DIR..."
mkdir -p "$ROOT_DIR"
cd "$ROOT_DIR"

# Array with configurations (e.g., android-version-kernel-version-date)
BUILD_CONFIGS=(
    #"android12-5.10-198-2024-01"
    #"android12-5.10-205-2024-03"
    #"android12-5.10-209-2024-05"
    #"android12-5.10-218-2024-08"

    #"android13-5.10-189-2023-11"
    #"android13-5.10-198-2024-01"
    #"android13-5.10-205-2024-03"
    #"android13-5.10-209-2024-05"
    #"android13-5.10-210-2024-06"
    #"android13-5.10-214-2024-07"
    #"android13-5.10-218-2024-08"

    #"android13-5.15-94-2023-05"
    "android13-5.15-123-2023-11"
    #"android13-5.15-137-2024-01"
    #"android13-5.15-144-2024-03"
    #"android13-5.15-148-2024-05"
    #"android13-5.15-149-2024-07"
    #"android13-5.15-151-2024-08"
    #"android13-5.15-167-2024-11"
    #"android13-5.15-173-lts"
    
    #"android14-5.15-131-2023-11"
    #"android14-5.15-137-2024-01"
    #"android14-5.15-144-2024-03"
    #"android14-5.15-148-2024-05"
    #"android14-5.15-149-2024-06"
    #"android14-5.15-153-2024-07"
    #"android14-5.15-158-2024-08"
    #"android14-5.15-167-2024-11"

    #"android14-6.1-25-2023-10"
    #"android14-6.1-43-2023-11"
    #"android14-6.1-57-2024-01"
    #"android14-6.1-68-2024-03"
    #"android14-6.1-75-2024-05"
    #"android14-6.1-78-2024-06"
    #"android14-6.1-84-2024-07"
    #"android14-6.1-90-2024-08"
    #"android14-6.1-112-2024-11"
    
    #"android15-6.6-30-2024-08"
)

# Arrays to store generated zip files, grouped by androidversion-kernelversion
declare -A RELEASE_ZIPS=()

# Iterate over configurations
build_config() {
    CONFIG=$1
    CONFIG_DETAILS=${CONFIG}

    # Create a directory named after the current configuration
    echo "Creating folder for configuration: $CONFIG..."
    mkdir -p "$CONFIG"
    cd "$CONFIG"
    
    # Split the config details into individual components
    IFS="-" read -r ANDROID_VERSION KERNEL_VERSION SUB_LEVEL DATE <<< "$CONFIG_DETAILS"
    
    # Formatted branch name for each build (e.g., android14-5.15-2024-01)
    FORMATTED_BRANCH="${ANDROID_VERSION}-${KERNEL_VERSION}-${DATE}"

    # Log file for this build in case of failure
    LOG_FILE="../${CONFIG}_build.log"

    echo "Starting build for $CONFIG using branch $FORMATTED_BRANCH..."
    # Check if AnyKernel3 repo exists, remove it if it does
    if [ -d "./AnyKernel3" ]; then
        echo "Removing existing AnyKernel3 directory..."
        rm -rf ./AnyKernel3
    fi
    echo "Cloning AnyKernel3 repository..."
    git clone https://github.com/TheWildJames/AnyKernel3.git -b "${ANDROID_VERSION}-${KERNEL_VERSION}"

    # Check if susfs4ksu repo exists, remove it if it does
    if [ -d "./susfs4ksu" ]; then
        echo "Removing existing susfs4ksu directory..."
        rm -rf ./susfs4ksu
    fi
    echo "Cloning susfs4ksu repository..."
    git clone https://gitlab.com/simonpunk/susfs4ksu.git -b "gki-${ANDROID_VERSION}-${KERNEL_VERSION}"

    # Check if kernel_patches repo exists, remove it if it does
    if [ -d "./kernel_patches" ]; then
        echo "Removing existing kernel_patches directory..."
        rm -rf ./kernel_patches
    fi
    echo "Cloning kernel_patches repository..."
    git clone https://github.com/TheWildJames/kernel_patches.git

    # Setup directory for each build
    SOURCE_DIR="/home/james/android_kernels/$CONFIG"

    # Check if the source directory exists and is a directory
    if [ -d "$SOURCE_DIR" ]; then
        # Copy the directory to the current working directory
        echo "Copying $SOURCE_DIR to ./"
        cp -r "$SOURCE_DIR" ./
        echo "Successfully copied $SOURCE_DIR to ./"
    else
        mkdir -p "$CONFIG"
    fi
    
    cd "$CONFIG"

    # Initialize and sync kernel source with updated repo commands
    echo "Initializing and syncing kernel source..."
    repo init --depth=1 --u https://android.googlesource.com/kernel/manifest -b common-${FORMATTED_BRANCH}
    REMOTE_BRANCH=$(git ls-remote https://android.googlesource.com/kernel/common ${FORMATTED_BRANCH})
    DEFAULT_MANIFEST_PATH=.repo/manifests/default.xml
    
    # Check if the branch is deprecated and adjust the manifest
    if grep -q deprecated <<< $REMOTE_BRANCH; then
        echo "Found deprecated branch: $FORMATTED_BRANCH"
        sed -i "s/\"${FORMATTED_BRANCH}\"/\"deprecated\/${FORMATTED_BRANCH}\"/g" $DEFAULT_MANIFEST_PATH
    fi

    # Verify repo version and sync
    repo --version
    repo --trace sync -c -j$(nproc --all) --no-tags --fail-fast

    # Apply KernelSU and SUSFS patches
    echo "Adding KernelSU..."
    curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU/next/kernel/setup.sh" | bash -s next
    #curl -LSs "https://raw.githubusercontent.com/backslashxx/KernelSU/magic/kernel/setup.sh" | bash -
    #curl -LSs "https://raw.githubusercontent.com/5ec1cff/KernelSU/main/kernel/setup.sh" | bash -

    echo "Applying SUSFS patches..."
    cp ../susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ./KernelSU-Next/
    cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-${ANDROID_VERSION}-${KERNEL_VERSION}.patch ./common/
    cp ../susfs4ksu/kernel_patches/fs/susfs.c ./common/fs/
    cp ../susfs4ksu/kernel_patches/include/linux/susfs.h ./common/include/linux/

    # Apply the patches
    cd ./KernelSU-Next
    if [ "${ANDROID_VERSION}" = "android14" ] && [ "${KERNEL_VERSION}" = "5.15" ]; then
        sed -i 's/KSU_EXPECTED_MAGIC_HASH := 7e0c6d7278a3bb8e364e0fcba95afaf3666cf5ff3c245a3b63c8833bd0445cc4/KSU_EXPECTED_MAGIC_HASH := 79e590113c4c4c0c222978e413a5faa801666957b1212a328e46c00c69821bf7/' ./10_enable_susfs_for_ksu.patch
        sed -i 's/KSU_EXPECTED_MAGIC_SIZE := 384/KSU_EXPECTED_MAGIC_SIZE := 998/' ./10_enable_susfs_for_ksu.patch
    fi
    patch -p1 --forward < 10_enable_susfs_for_ksu.patch || true
    cd ../common
    patch -p1 < 50_add_susfs_in_gki-${ANDROID_VERSION}-${KERNEL_VERSION}.patch || true

    #adding lineage patch
    cp ../../kernel_patches/69_hide_stuff.patch ./
    patch -p1 -F 3 < 69_hide_stuff.patch
    cp ../../kernel_patches/ksu_hooks.patch ./
    patch -p1 -F 3 < ksu_hooks.patch

    cd ..
    if [ "${ANDROID_VERSION}" = "android14" ] && [ "${KERNEL_VERSION}" = "6.1" ]; then
        echo "Skipping selinux.c patch fix"
    else
        cp ../kernel_patches/selinux.c_fix.patch ./
        patch -p1 -F 3 < selinux.c_fix.patch
    fi
    if [ "${ANDROID_VERSION}" = "android14" ] && [ "${KERNEL_VERSION}" = "5.15" ]; then
        echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> ./common/arch/arm64/configs/zuma_defconfig
        cp ../kernel_patches/apk_sign.c_fix.patch ./
        patch -p1 -F 3 < apk_sign.c_fix.patch
    else
        echo "Skipping KSU_SUSFS_HAS_MAGIC_MOUNT=y"
        echo "Skipping apk_sign.c_fix.patch"
    fi
    cp ../kernel_patches/kernel_compat.c_fix.patch ./
    patch -p1 --fuzz=3 < ./kernel_compat.c_fix.patch

    sed -i 's/#ifdef CONFIG_KPROBES/#if 0/g' ./KernelSU-Next/kernel/core_hook.c
    sed -i 's/#ifdef CONFIG_KPROBES/#if 0/g' ./KernelSU-Next/kernel/ksu.c
    sed -i 's/#ifdef CONFIG_KPROBES/#if 0/g' ./KernelSU-Next/kernel/ksud.c
    sed -i 's/#ifdef CONFIG_KPROBES/#if 0/g' ./KernelSU-Next/kernel/sucompat.c

    # Add configuration settings for SUSFS
    echo "Adding configuration settings to gki_defconfig..."
    echo "CONFIG_KSU=y" >> ./common/arch/arm64/configs/gki_defconfig
    echo "CONFIG_KSU_SUSFS=y" >> ./common/arch/arm64/configs/gki_defconfig
    echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> ./common/arch/arm64/configs/gki_defconfig
    echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
    echo "KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=n" >> ./common/arch/arm64/configs/gki_defconfig
    echo "KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=n" >> ./common/arch/arm64/configs/gki_defconfig
    echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> ./common/arch/arm64/configs/gki_defconfig
    echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=y" >> ./common/arch/arm64/configs/gki_defconfig
    echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
    echo "KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=n" >> ./common/arch/arm64/configs/gki_defconfig
    echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> ./common/arch/arm64/configs/gki_defconfig
    echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> ./common/arch/arm64/configs/gki_defconfig
    echo "KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> ./common/arch/arm64/configs/gki_defconfig
    echo "KSU_SUSFS_SPOOF_BOOTCONFIG=y" >> ./common/arch/arm64/configs/gki_defconfig
    echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> ./common/arch/arm64/configs/gki_defconfig
    echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> ./common/arch/arm64/configs/gki_defconfig

    # Build kernel
    echo "Building kernel for $CONFIG..."

    # Check if build.sh exists, if it does, run the default build script
    if [ -e build/build.sh ]; then
        echo "build.sh found, running default build script..."
        # Modify config files for the default build process
        sed -i '2s/check_defconfig//' ./common/build.config.gki
        sed -i "s/dirty/'Wild+'/g" ./common/scripts/setlocalversion
        LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh
    
        # Copying to AnyKernel3
        echo "Copying Image.lz4 to $CONFIG/AnyKernel3..."

        # Check if the boot.img file exists
        if [ "$ANDROID_VERSION" = "android12" ]; then
            mkdir bootimgs
            cp ./out/${ANDROID_VERSION}-${KERNEL_VERSION}/dist/Image ./bootimgs
            cp ./out/${ANDROID_VERSION}-${KERNEL_VERSION}/dist/Image.lz4 ./bootimgs
            cp ./out/${ANDROID_VERSION}-${KERNEL_VERSION}/dist/Image ../
            cp ./out/${ANDROID_VERSION}-${KERNEL_VERSION}/dist/Image.lz4 ../
            gzip -n -k -f -9 ../Image >../Image.gz
            cd ./bootimgs
            
            GKI_URL=https://dl.google.com/android/gki/gki-certified-boot-android12-5.10-"${DATE}"_r1.zip
            FALLBACK_URL=https://dl.google.com/android/gki/gki-certified-boot-android12-5.10-2023-01_r1.zip
            status=$(curl -sL -w "%{http_code}" "$GKI_URL" -o /dev/null)
                
            if [ "$status" = "200" ]; then
                curl -Lo gki-kernel.zip "$GKI_URL"
            else
                echo "[+] $GKI_URL not found, using $FALLBACK_URL"
                curl -Lo gki-kernel.zip "$FALLBACK_URL"
            fi
                
                unzip gki-kernel.zip && rm gki-kernel.zip
                echo 'Unpack prebuilt boot.img'
                unpack_bootimg.py --boot_img="./boot-5.10.img"
                
                echo 'Building Image.gz'
                gzip -n -k -f -9 Image >Image.gz
                
                echo 'Building boot.img'
                mkbootimg.py --header_version 4 --kernel Image --output boot.img --ramdisk out/ramdisk --os_version 12.0.0 --os_patch_level "${DATE}"
                avbtool.py add_hash_footer --partition_name boot --partition_size $((64 * 1024 * 1024)) --image boot.img --algorithm SHA256_RSA2048 --key /home/james/keys/testkey_rsa2048.pem
                cp ./boot.img ../../../${ANDROID_VERSION}-${KERNEL_VERSION}.${SUB_LEVEL}_${DATE}-boot.img
                
                echo 'Building boot-gz.img'
                mkbootimg.py --header_version 4 --kernel Image.gz --output boot-gz.img --ramdisk out/ramdisk --os_version 12.0.0 --os_patch_level "${DATE}"
            	avbtool.py add_hash_footer --partition_name boot --partition_size $((64 * 1024 * 1024)) --image boot-gz.img --algorithm SHA256_RSA2048 --key /home/james/keys/testkey_rsa2048.pem
                cp ./boot-gz.img ../../../${ANDROID_VERSION}-${KERNEL_VERSION}.${SUB_LEVEL}_${DATE}-boot-gz.img

                echo 'Building boot-lz4.img'
                mkbootimg.py --header_version 4 --kernel Image.lz4 --output boot-lz4.img --ramdisk out/ramdisk --os_version 12.0.0 --os_patch_level "${DATE}"
                avbtool.py add_hash_footer --partition_name boot --partition_size $((64 * 1024 * 1024)) --image boot-lz4.img --algorithm SHA256_RSA2048 --key /home/james/keys/testkey_rsa2048.pem
                cp ./boot-lz4.img ../../../${ANDROID_VERSION}-${KERNEL_VERSION}.${SUB_LEVEL}_${DATE}-boot-lz4.img
                cd ..

        elif [ "$ANDROID_VERSION" = "android13" ]; then
            mkdir bootimgs
            cp ./out/${ANDROID_VERSION}-${KERNEL_VERSION}/dist/Image ./bootimgs
            cp ./out/${ANDROID_VERSION}-${KERNEL_VERSION}/dist/Image.lz4 ./bootimgs
            cp ./out/${ANDROID_VERSION}-${KERNEL_VERSION}/dist/Image ../
            cp ./out/${ANDROID_VERSION}-${KERNEL_VERSION}/dist/Image.lz4 ../
            gzip -n -k -f -9 ../Image >../Image.gz
            cd ./bootimgs

            echo 'Building Image.gz'
            gzip -n -k -f -9 Image >Image.gz

            echo 'Building boot.img'
            mkbootimg.py --header_version 4 --kernel Image --output boot.img
            avbtool.py add_hash_footer --partition_name boot --partition_size $((64 * 1024 * 1024)) --image boot.img --algorithm SHA256_RSA2048 --key /home/james/keys/testkey_rsa2048.pem
            cp ./boot.img ../../../${ANDROID_VERSION}-${KERNEL_VERSION}.${SUB_LEVEL}_${DATE}-boot.img
            
            echo 'Building boot-gz.img'
            mkbootimg.py --header_version 4 --kernel Image.gz --output boot-gz.img
        	avbtool.py add_hash_footer --partition_name boot --partition_size $((64 * 1024 * 1024)) --image boot-gz.img --algorithm SHA256_RSA2048 --key /home/james/keys/testkey_rsa2048.pem
            cp ./boot-gz.img ../../../${ANDROID_VERSION}-${KERNEL_VERSION}.${SUB_LEVEL}_${DATE}-boot-gz.img

            echo 'Building boot-lz4.img'
            mkbootimg.py --header_version 4 --kernel Image.lz4 --output boot-lz4.img
            avbtool.py add_hash_footer --partition_name boot --partition_size $((64 * 1024 * 1024)) --image boot-lz4.img --algorithm SHA256_RSA2048 --key /home/james/keys/testkey_rsa2048.pem
            cp ./boot-lz4.img ../../../${ANDROID_VERSION}-${KERNEL_VERSION}.${SUB_LEVEL}_${DATE}-boot-lz4.img
            cd ..
        fi
    else
        # Use Bazel build if build.sh exists
        echo "Running Bazel build..."
        sed -i "/stable_scmversion_cmd/s/-maybe-dirty/-Wild+/g" ./build/kernel/kleaf/impl/stamp.bzl
        sed -i '2s/check_defconfig//' ./common/build.config.gki
        rm -rf ./common/android/abi_gki_protected_exports_aarch64
        rm -rf ./common/android/abi_gki_protected_exports_x86_64
        tools/bazel build --config=fast //common:kernel_aarch64_dist
        

        # Creating Boot imgs
        echo "Creating boot.imgs..."
        if [ "$ANDROID_VERSION" = "android14" ]; then
            mkdir bootimgs
            cp ./bazel-bin/common/kernel_aarch64/Image ./bootimgs
            cp ./bazel-bin/common/kernel_aarch64/Image.lz4 ./bootimgs
            cp ./bazel-bin/common/kernel_aarch64/Image ../
            cp ./bazel-bin/common/kernel_aarch64/Image.lz4 ../
            gzip -n -k -f -9 ../Image >../Image.gz
            cd ./bootimgs

            echo 'Building Image.gz'
            gzip -n -k -f -9 Image >Image.gz

            echo 'Building boot.img'
            mkbootimg.py --header_version 4 --kernel Image --output boot.img
            avbtool.py add_hash_footer --partition_name boot --partition_size $((64 * 1024 * 1024)) --image boot.img --algorithm SHA256_RSA2048 --key /home/james/keys/testkey_rsa2048.pem
            cp ./boot.img ../../../${ANDROID_VERSION}-${KERNEL_VERSION}.${SUB_LEVEL}_${DATE}-boot.img
            
            echo 'Building boot-gz.img'
            mkbootimg.py --header_version 4 --kernel Image.gz --output boot-gz.img
        	avbtool.py add_hash_footer --partition_name boot --partition_size $((64 * 1024 * 1024)) --image boot-gz.img --algorithm SHA256_RSA2048 --key /home/james/keys/testkey_rsa2048.pem
            cp ./boot-gz.img ../../../${ANDROID_VERSION}-${KERNEL_VERSION}.${SUB_LEVEL}_${DATE}-boot-gz.img

            echo 'Building boot-lz4.img'
            mkbootimg.py --header_version 4 --kernel Image.lz4 --output boot-lz4.img
            avbtool.py add_hash_footer --partition_name boot --partition_size $((64 * 1024 * 1024)) --image boot-lz4.img --algorithm SHA256_RSA2048 --key /home/james/keys/testkey_rsa2048.pem
            cp ./boot-lz4.img ../../../${ANDROID_VERSION}-${KERNEL_VERSION}.${SUB_LEVEL}_${DATE}-boot-lz4.img
            cd ..
        fi
    fi

    # Create zip in the same directory
    cd ../AnyKernel3
    ZIP_NAME="AnyKernel3-${ANDROID_VERSION}-${KERNEL_VERSION}.${SUB_LEVEL}_${DATE}.zip"
    echo "Creating zip file: $ZIP_NAME..."
    mv ../Image ./Image 
    zip -r "../../$ZIP_NAME" ./*
    rm ./Image
    ZIP_NAME="AnyKernel3-lz4-${ANDROID_VERSION}-${KERNEL_VERSION}.${SUB_LEVEL}_${DATE}.zip"
    echo "Creating zip file: $ZIP_NAME..."
    mv ../Image.lz4 ./Image.lz4 
    zip -r "../../$ZIP_NAME" ./*
    rm ./Image.lz4
    ZIP_NAME="AnyKernel3-gz-${ANDROID_VERSION}-${KERNEL_VERSION}.${SUB_LEVEL}_${DATE}.zip"
    echo "Creating zip file: $ZIP_NAME..."
    mv ../Image.gz ./Image.gz 
    zip -r "../../$ZIP_NAME" ./*
    rm ./Image.gz
    cd ../../

    RELEASE_ZIPS["$ANDROID_VERSION-$KERNEL_VERSION.$SUB_LEVEL"]+="./$ZIP_NAME "

    # Delete the $CONFIG folder after building
    echo "Deleting $CONFIG folder..."
    #rm -rf "$CONFIG"
}

#并发生成管理
对于“${build_CONFIGS[@]}”中的配置；执行"${BUILD_CONFIGS[@]}"；do
#后台启动构建过程#在后台启动生成过程
build_config"$CONFIG"&"$CONFIG" &

#将并行作业限制为$Max_CONCURRENT_BUILDS#将并发作业限制为$Max_CONCURRENT_BUILDS
while(($(jobs-r|wc-l)>=MAX_CONCURRENT_BUILDS)；do
sleep1#每秒检查一次空闲插槽#每秒检查一次空闲插槽
已完成
已完成

等待

回声"生成过程完成。""生成过程完成。"

出口

#收集所有zip和img文件
文件=($(find./-type f\(-name"*.zip"-o-name"*.img"\)))"*.zip"-o-name"*.img" \)))

#GitHub存储库详细信息
repo_OWNER="TheWildJames""TheWildJames"
repo_NAME="GKI_KernelSU_SUSFS""GKI_KernelSU_SUSFS"
tag_NAME=v$(日期+"%Y.%m.%d-%H%M%S")v$(日期+"%Y.%m.%d-%H%M%S")
release_NAME="带有KernelSU和SUSFS v1.5.3的GKI内核""GKI内核，带Kernelsu和SUSFS v1.5.3"
release_NOTES="此版本包含KernelSU和SUSFS v1.5.3"此版本包含KernelSU和SUSFS v1.5.3
笔记: 注：6.1内核仍在1.5.2上

模块: 
https://github.com/sidex15/ksu_module_susfs
笔记: 注：使用1.5.2至1.5.3
笔记: 注：6.1内核使用r10以获得最佳兼容性

经理: 
https://github.com/rifsxd/KernelSU-Next
https://github.com/rsuntk/KernelSU

功能:
[[+]KernelSu-Next]KernelSu-Next
[[+]SUSFS v1.5.3]SUSFS v1.5.3
[[+]内置SUS_su模式2(将表示在模块中禁用)]内置SUS_su模式2(将表示在模块中禁用)
[[+]WireGuard支架]WireGuard支架
[[+]Maphide LineageOS检测]Maphide LineageOS检测
[[+]用于jit-zygote-cache检测的无效马菲德]用于jit-zygote-cache检测的无用马菲德
[[+]魔法Mount(必须删除/data/adb/ksu/modules.img和/data/adb/modules)]魔法Mount(必须删除/data/adb/ksu/modules.img和/data/adb/modules)
"

#创建GitHub版本
echo"创建GitHub发布: 回声"正在创建GitHub版本：$release_NAME...""
GH版本创建"$TAG_NAME""${文件[@]}”\"$TAG_NAME" "${文件[@]}" \
--repo"$REPO_OWNER/$REPO_NAME"\"$REPO_OWNER/$REPO_NAME" \
--title"$RELEASE_NAME"\"$RELEASE_NAME" \
--注释"$RELEASE_NOTES""$RELEASE_NOTES"

回声"使用以下文件创建的GitHub版本：""使用以下文件创建的GitHub版本："
printf“%s”\n“”${文件[@]}""%s\n""${文件[@]}"

